import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Background from './components/Background';
import NavigationTabs, { routes } from './components/navigation-tabs';
import Hero from './components/hero';
import Logo from './components/logo';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} w-screen h-screen`}>
        <Background>
          <div className='flex flex-col md:flex-row p-7'>
            <div className='md:w-1/2 h-screen flex flex-col'>
              <Link className='w-24 h-24' href={routes.get('home')!.path}>
                <Logo />
              </Link>
              <div className='h-1/2 flex flex-col justify-center'>
                <Hero />
              </div>
              <div className='h-1/2 flex flex-col justify-center'>
                <NavigationTabs />
              </div>
            </div>
            <main className='flex min-h-screen flex-col items-center justify-between p-24'>
              {children}
            </main>
          </div>
        </Background>
      </body>
    </html>
  );
}
